CREATE TABLE Users(uname VARCHAR(20) PRIMARY KEY, pwHash VARBINARY(max), pwSalt VARBINARY(max), balance INT);
CREATE TABLE Reservations(rid INT PRIMARY KEY, paid BIT, uname VARCHAR(20) REFERENCES Users, flight1 INT REFERENCES FLIGHTS, flight2 INT REFERENCES FLIGHTS);
CREATE TABLE ReservationID(rid INT PRIMARY KEY)